name: Terraform Deployment

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7 # Update to your Terraform version

      # Terraform Formatting Check
      - name: Check Terraform formatting
        run: terraform fmt -check

      # Terraform Init
      - name: Terraform Initialization
        run: terraform init

      # Terraform Validation
      - name: Terraform Validation
        run: terraform validate

  deploy:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7 # Update to your Terraform version

      # Terraform Init
      - name: Terraform Initialization
        run: terraform init

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Terraform Apply
      - name: Terraform Apply
        env:
          TF_VAR_YOUR_VARIABLE: ${{ secrets.TF_VAR_YOUR_VARIABLE }}
        run: terraform apply -auto-approve tfplan

