name: Terraform Deploy and PR Validation

on:
  pull_request:
    paths:
      - '**/*.tf'   # Trigger when Terraform files are modified
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main   # Trigger deploy on main branch when merged

jobs:
  terraform-pr-validation:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'  # Specify Terraform version

      # Install Terraform dependencies (modules)
      - name: Install Terraform dependencies
        run: terraform init

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Optional: Plan and check if PR includes any breaking changes
      - name: Terraform Plan
        run: terraform plan -out=tfplan

  terraform-deploy:
    runs-on: ubuntu-latest
    needs: terraform-pr-validation
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Only deploy on push to main branch
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'  # Specify Terraform version

      # Install Terraform dependencies (modules)
      - name: Install Terraform dependencies
        run: terraform init

      # Terraform plan and apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_secret_key: ${{ secrets.TF_SECRET_KEY }}  # Use GitHub Secrets for sensitive values
