---
- name: Install Node Exporter on Servers
  hosts: all
  become: true  # Run as root
  tasks:
    - name: Download Node Exporter binary
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz

    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Create node_exporter user
      user:
        name: node_exporter
        shell: /bin/false
        system: yes

    - name: Move node_exporter binary to /usr/local/bin
      command: mv /opt/node_exporter-1.8.1.linux-amd64/node_exporter /usr/local/bin/

    - name: Set permissions for node_exporter binary
      file:
        path: /usr/local/bin/node_exporter
        owner: node_exporter
        group: node_exporter
        mode: '0755'

    - name: Create systemd service for node_exporter
      copy:
        content: |
          [Unit]
          Description=Prometheus Node Exporter
          After=network.target

          [Service]
          User=node_exporter
          ExecStart=/usr/local/bin/node_exporter
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/node_exporter.service
        mode: '0644'

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Start and enable node_exporter service
      systemd:
        name: node_exporter
        state: started
        enabled: yes
